### ISSUE TITLE
Use low, high insteade of left, right

### ISSUE THREAD

**Issue by Ali-Ibrahim137** [Omar622/Random-generator#3]
Looking at the code, examples, and docs I find it little bit annoying to use variable names *left*, and *right*.
I suggest other names, something like *low*, and *high* would be better.
Let me know your thoughts, if you have a better naming please suggest it.
I can submit a PR if you agree the changes.

**Comment by Omar622** [comment]
well, it makes more sense. I agree the changes kindly submit a PR.
Thank you for your interest in the library.

**Comment by Omar622** [comment]
I merged your PR. thank you again.
I added your name and GitHub link in the updated by section in the function's docs in README file.
